#!/usr/bin/env python3
"""Per-generator census of the cached gasstation weeks (Phase 0 leak scan).

The no-degradation experiment's zero-shot claim dies if validator traffic
generated by the target model (gemini-3.1-flash-lite) sits inside the
gasstation training pool. The manifest cannot answer this -- build_manifest
keeps only `source_file` from sample metadata -- but the CACHE can: gasbench's
writer stores per-sample `model_name` (+ `iso_week`, `generator_hotkey`) in
each week's sample_metadata.json. This script counts model_name per week,
flags samples matching --pattern, and can emit a shell script that moves the
flagged files aside so the next build_manifest never sees them.

Usage (remote box):
    python scan_gasstation_generators.py --cache-dir /workspace/data/datasets
    python scan_gasstation_generators.py --cache-dir ... \
        --pattern gemini --emit-mv quarantine_gemini.sh
    bash quarantine_gemini.sh        # then rebuild the manifest

Exit status: 1 only if a matching sample file EXISTS on disk -- i.e. the next
build_manifest would ingest it (rows whose file is gone are skipped there,
build_manifest.py:450-452). Metadata matches whose file is already
moved/pruned are reported but do not fail the gate, so the scan converges to
exit 0 after the quarantine script runs.
"""
from __future__ import annotations

import argparse
import json
import re
import shlex
import sys
from collections import Counter, defaultdict
from pathlib import Path


def load_meta(week_dir: Path) -> dict:
    p = week_dir / "sample_metadata.json"
    if not p.is_file():
        return {}
    with open(p) as f:
        doc = json.load(f)
    # Both observed shapes: {filename: {...}} and [{...}, ...] with a
    # source_file/filename field per record.
    if isinstance(doc, list):
        out = {}
        for i, m in enumerate(doc):
            key = m.get("source_file") or m.get("filename") or str(i)
            out[key] = m
        return out
    return doc


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--cache-dir", required=True,
                    help="gasbench cache root (the dir holding datasets/, or "
                         "the datasets dir itself)")
    ap.add_argument("--dataset", default="gasstation-generated-images")
    ap.add_argument("--pattern", default="gemini",
                    help="case-insensitive regex over model_name; matches are "
                         "the leak (default: gemini)")
    ap.add_argument("--emit-mv", default=None, metavar="OUT.SH",
                    help="write a shell script that moves every flagged "
                         "sample file (and prints one comment per file) into "
                         "<week>/quarantined-<pattern>/ next to its samples/ "
                         "dir. Review, then run with bash.")
    args = ap.parse_args()

    root = Path(args.cache_dir)
    ds = root / args.dataset
    if not ds.is_dir() and (root / "datasets" / args.dataset).is_dir():
        ds = root / "datasets" / args.dataset
    if not ds.is_dir():
        raise SystemExit(f"no {args.dataset} under {root} (or {root}/datasets)")

    rx = re.compile(args.pattern, re.I)
    weeks = sorted(d for d in ds.iterdir() if d.is_dir()
                   and (d / "sample_metadata.json").is_file())
    # A flat (un-weeked) checkout is one "week" named after the dataset.
    if not weeks and (ds / "sample_metadata.json").is_file():
        weeks = [ds]
    if not weeks:
        raise SystemExit(f"{ds}: no week dirs with sample_metadata.json")

    per_week: dict[str, Counter] = defaultdict(Counter)
    flagged: list[tuple[Path, str]] = []          # (samples-file path, model)
    for wd in weeks:
        meta = load_meta(wd)
        for fname, m in meta.items():
            model = str((m or {}).get("model_name") or "<missing>")
            per_week[wd.name][model] += 1
            if rx.search(model):
                fp = wd / "samples" / Path(str(fname)).name
                flagged.append((fp, model))

    print(f"{ds}\n{'-' * 72}")
    for week in sorted(per_week):
        c = per_week[week]
        total = sum(c.values())
        print(f"{week}  ({total:,} samples, {len(c)} generators)")
        for model, n in c.most_common():
            mark = "  <-- MATCHES" if rx.search(model) else ""
            print(f"    {model:52s} {n:>7,}{mark}")
    print("-" * 72)

    if not flagged:
        print(f"clean: no model_name matches /{args.pattern}/i in "
              f"{len(weeks)} week(s)")
        return
    live = [(p, m) for p, m in flagged if p.is_file()]
    gone = len(flagged) - len(live)
    if gone:
        print(f"note: {gone} matching metadata row(s) have no file on disk "
              f"(already quarantined/pruned) -- build_manifest skips those")
    if not live:
        print(f"clean for manifest purposes: all {len(flagged)} matches are "
              f"file-less metadata rows")
        return
    flagged = live
    print(f"LEAK: {len(flagged)} on-disk sample(s) match /{args.pattern}/i")
    if args.emit_mv:
        safe = re.sub(r"[^A-Za-z0-9_-]", "_", args.pattern)
        with open(args.emit_mv, "w") as f:
            f.write("#!/bin/bash\nset -euo pipefail\n")
            for fp, model in flagged:
                if not fp.is_file():
                    continue
                qdir = fp.parent.parent / f"quarantined-{safe}"
                f.write(f"# {model}\nmkdir -p {shlex.quote(str(qdir))}\n"
                        f"mv {shlex.quote(str(fp))} {shlex.quote(str(qdir))}/\n")
        print(f"  wrote {args.emit_mv} -- review, bash it, then REBUILD the "
              f"manifest (metadata rows without files are skipped by "
              f"build_manifest)")
    sys.exit(1)


if __name__ == "__main__":
    main()
